### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by uhlhosting** [tierpod/dmarc-report-converter#35]
```
[eofs@cp bottega.eofs.dev]$ go get -u github.com/tierpod/dmarc-report-converter
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

Running latest. go 

```
[eofs@cp bottega.eofs.dev]$ go version
go version go1.20.5 linux/amd64
```

**Comment by uhlhosting** [comment]
I managed to deploy it, yet I cannot seem to establish a connection to the IMAP inbox. I tried with cpanel connections with SSL/TLS port and unsecured, it timeouts.

**Comment by tierpod** [comment]
Hi @uhlhosting ,

Sorry for late answer.

> 'go get' is no longer supported outside a module.

Thank you, I'll update installation process for new go versions.

>  I cannot seem to establish a connection to the IMAP inbox

Could you please run in debug mode, attach the errors and config (without sensitive data like password, of course)? I believe that timeout error can be caused by network connectivity problems. You can investigate it:

* At first, ping you email server `ping imap.example.com`
* Try to telnet into it

```
telnet imap.example.com 143
```

Of course, replace imap.example.com with your server name or address, and 143 with imap port
